# Generated by Django 3.2.9 on 2021-11-20 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('continent', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('area', models.DecimalField(decimal_places=2, max_digits=9)),
                ('population', models.PositiveIntegerField()),
                ('continent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='continent.continent')),
            ],
        ),
    ]
